/-
Copyright (c) 2026 Lars Warren Ericson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/

import Scott1964.MeasurementStructures.Probability.Basic
import Mathlib.Order.PrimeSeparator
import Mathlib.Topology.Bornology.BoundedOperation
import Mathlib.Topology.ContinuousMap.Bounded.Basic

/-!
# Universal event spaces for an infinite Boolean algebra

This file supplies two complementary universal realizations of a Boolean algebra.

* `PrimePoint B` and `stoneIndicator` are the usual Stone representation by
  characteristic functions on prime ideals.  This representation is faithful and is
  convenient for stating Scott's finite-sum cancellation condition.
* `ProbabilityPoint B` and `eventVector` evaluate an event at every finitely additive
  probability.  Their real span is a normed order-unit space on which probabilities
  are exactly the point-evaluation positive normalized continuous linear functionals.

The second realization is used for the elementary, choice-free state correspondence
below.  Constructing the analogous functional on the Stone-indicator span requires
the separate simple-function integration theorem for arbitrary finitely additive
charges.
-/

namespace Scott1964.MeasurementStructures.Probability.Infinite

open scoped BoundedContinuousFunction
open Set

noncomputable section

universe u

variable (B : Type u) [BooleanAlgebra B]

/-! ## The probability-evaluation event space -/

noncomputable instance instBoundedAddReal : BoundedAdd ℝ := inferInstance

/-- A point of the universal probability-evaluation space. -/
def ProbabilityPoint :=
  {μ : B → ℝ // IsFinitelyAdditiveProbability μ}

instance instTopologicalSpaceProbabilityPoint : TopologicalSpace (ProbabilityPoint B) := ⊥

theorem probabilityPoint_discrete_eq_bot :
    instTopologicalSpaceProbabilityPoint B = ⊥ :=
  rfl

instance instDiscreteTopologyProbabilityPoint : DiscreteTopology (ProbabilityPoint B) where
  eq_bot := probabilityPoint_discrete_eq_bot B

noncomputable instance instAddCommMonoidProbabilityBCF :
    AddCommMonoid (ProbabilityPoint B →ᵇ ℝ) := inferInstance

noncomputable instance instModuleProbabilityBCF :
    Module ℝ (ProbabilityPoint B →ᵇ ℝ) := inferInstance

noncomputable instance instAddCommGroupProbabilityBCF :
    AddCommGroup (ProbabilityPoint B →ᵇ ℝ) := inferInstance

theorem probabilityPoint_nonnegative (p : ProbabilityPoint B) (a : B) :
    0 ≤ p.1 a :=
  p.2.nonnegative a

theorem probabilityPoint_le_one (p : ProbabilityPoint B) (a : B) :
    p.1 a ≤ 1 :=
  p.2.le_one a

theorem eventVector_dist_le_one (a : B) (p q : ProbabilityPoint B) :
    dist (p.1 a) (q.1 a) ≤ 1 := by
  rw [Real.dist_eq, abs_sub_le_iff]
  constructor <;>
    linarith [probabilityPoint_nonnegative B p a,
      probabilityPoint_nonnegative B q a,
      probabilityPoint_le_one B p a,
      probabilityPoint_le_one B q a]

/-- The universal evaluation vector `μ ↦ μ(a)` of an event. -/
def eventVector (a : B) : ProbabilityPoint B →ᵇ ℝ :=
  BoundedContinuousFunction.mkOfDiscrete (fun p => p.1 a) 1
    (eventVector_dist_le_one B a)

/-- The real normed space generated by universal event-evaluation vectors. -/
def EventSpan : Submodule ℝ (ProbabilityPoint B →ᵇ ℝ) :=
  Submodule.span ℝ (Set.range (eventVector B))

noncomputable instance instNormedAddCommGroupEventSpan :
    NormedAddCommGroup (EventSpan B) := inferInstance

noncomputable instance instNormedSpaceEventSpan :
    NormedSpace ℝ (EventSpan B) := inferInstance

noncomputable instance instLocallyConvexSpaceEventSpan :
    LocallyConvexSpace ℝ (EventSpan B) := inferInstance

/-- The event vector as an element of `EventSpan`. -/
def event (a : B) : EventSpan B :=
  ⟨eventVector B a, Submodule.subset_span (Set.mem_range_self a)⟩

/-! ## Stone points and indicator vectors -/

/-- A Stone point of `B`, presented as a prime (equivalently maximal) ideal. -/
structure PrimePoint where
  ideal : Order.Ideal B
  isPrime : ideal.IsPrime

instance : TopologicalSpace (PrimePoint B) := ⊥

instance : DiscreteTopology (PrimePoint B) := ⟨rfl⟩

/-- The `0`/`1` value of an event at a Stone point. -/
def stoneValue (a : B) (p : PrimePoint B) : ℝ :=
  @ite ℝ (a ∈ p.ideal) (Classical.propDecidable (a ∈ p.ideal)) 0 1

/-- The characteristic vector of an event on the Stone points of `B`.

The convention is that a point lies in the event `a` exactly when its prime ideal
does not contain `a`.
-/
def stoneIndicator (a : B) : PrimePoint B →ᵇ ℝ :=
  by
    classical
    exact BoundedContinuousFunction.mkOfDiscrete
      (stoneValue B a) 1 (by
        intro p q
        simp only [stoneValue, Real.dist_eq]
        split <;> split <;> norm_num)

@[simp]
theorem stoneIndicator_apply (a : B) (p : PrimePoint B) :
    stoneIndicator B a p = stoneValue B a p :=
  rfl

@[simp]
theorem stoneIndicator_bot : stoneIndicator B (⊥ : B) = 0 := by
  classical
  ext p
  simp [stoneIndicator, stoneValue]

@[simp]
theorem stoneIndicator_top : stoneIndicator B (⊤ : B) = 1 := by
  classical
  ext p
  have hp : (⊤ : B) ∉ p.ideal := p.isPrime.toIsProper.top_notMem
  simp [stoneIndicator, stoneValue, hp]

@[simp]
theorem stoneIndicator_sup_of_disjoint {a b : B} (h : Disjoint a b) :
    stoneIndicator B (a ⊔ b) = stoneIndicator B a + stoneIndicator B b := by
  classical
  ext p
  have hp := p.isPrime
  by_cases ha : a ∈ p.ideal
  · by_cases hb : b ∈ p.ideal
    · simp [stoneIndicator, stoneValue, ha, hb, Order.Ideal.sup_mem ha hb]
    · have hab : a ⊔ b ∉ p.ideal := fun hs => hb (p.ideal.lower le_sup_right hs)
      simp [stoneIndicator, stoneValue, ha, hb, hab]
  · by_cases hb : b ∈ p.ideal
    · have hab : a ⊔ b ∉ p.ideal := fun hs => ha (p.ideal.lower le_sup_left hs)
      simp [stoneIndicator, stoneValue, ha, hb, hab]
    · have hab : a ⊔ b ∉ p.ideal := fun hs => ha (p.ideal.lower le_sup_left hs)
      have hnotboth : ¬(a ∉ p.ideal ∧ b ∉ p.ideal) := by
        intro hn
        have hi : a ⊓ b ∈ p.ideal := by
          rw [h.eq_bot]
          exact p.ideal.bot_mem
        exact (hp.mem_or_mem hi).elim hn.1 hn.2
      exact (hnotboth ⟨ha, hb⟩).elim

/-- Stone indicators separate events, so the Stone representation is faithful. -/
theorem stoneIndicator_injective : Function.Injective (stoneIndicator B) := by
  classical
  intro a b hab
  apply le_antisymm
  · by_contra hle
    have hd : Disjoint
        ((Order.PFilter.principal a : Order.PFilter B) : Set B)
        ((Order.Ideal.principal b : Order.Ideal B) : Set B) := by
      rw [Set.disjoint_left]
      intro x hax hxb
      exact hle ((Order.PFilter.mem_principal.mp hax).trans
        (Order.Ideal.mem_principal.mp hxb))
    obtain ⟨J, hJ, hbJ, hdis⟩ :=
      DistribLattice.prime_ideal_of_disjoint_filter_ideal hd
    let p : PrimePoint B := ⟨J, hJ⟩
    have hbin : b ∈ J := hbJ Order.Ideal.mem_principal_self
    have hain : a ∉ J := by
      intro haJ
      exact Set.disjoint_left.mp hdis
        (show a ∈ Order.PFilter.principal a by
          rw [Order.PFilter.mem_principal]) haJ
    have := congrArg (fun f : PrimePoint B →ᵇ ℝ => f p) hab
    simp [stoneIndicator, stoneValue, p, hbin, hain] at this
  · by_contra hle
    have hd : Disjoint
        ((Order.PFilter.principal b : Order.PFilter B) : Set B)
        ((Order.Ideal.principal a : Order.Ideal B) : Set B) := by
      rw [Set.disjoint_left]
      intro x hbx hxa
      exact hle ((Order.PFilter.mem_principal.mp hbx).trans
        (Order.Ideal.mem_principal.mp hxa))
    obtain ⟨J, hJ, haJ, hdis⟩ :=
      DistribLattice.prime_ideal_of_disjoint_filter_ideal hd
    let p : PrimePoint B := ⟨J, hJ⟩
    have hain : a ∈ J := haJ Order.Ideal.mem_principal_self
    have hbin : b ∉ J := by
      intro hbJ
      exact Set.disjoint_left.mp hdis
        (show b ∈ Order.PFilter.principal b by
          rw [Order.PFilter.mem_principal]) hbJ
    have := congrArg (fun f : PrimePoint B →ᵇ ℝ => f p) hab
    simp [stoneIndicator, stoneValue, p, hbin, hain] at this

/-- Equality of two finite sums of event indicators. -/
def IndicatorSumEqual {ι : Type*} [Fintype ι] (x y : ι → B) : Prop :=
  ∑ i, stoneIndicator B (x i) = ∑ i, stoneIndicator B (y i)

theorem indicatorSumEqual_iff {ι : Type*} [Fintype ι] (x y : ι → B) :
    IndicatorSumEqual B x y ↔
      ∀ p : PrimePoint B,
        ∑ i, stoneValue B (x i) p =
          ∑ i, stoneValue B (y i) p := by
  classical
  constructor
  · intro h p
    have := congrArg (fun f : PrimePoint B →ᵇ ℝ => f p) h
    simpa [IndicatorSumEqual, stoneIndicator, stoneValue] using this
  · intro h
    apply BoundedContinuousFunction.ext
    intro p
    simpa [IndicatorSumEqual, stoneIndicator, stoneValue] using h p

/-- The two-valued finitely additive probability associated with a Stone point. -/
def primeProbability (p : PrimePoint B) : ProbabilityPoint B := by
  refine ⟨fun a => stoneValue B a p, ?_⟩
  refine
    { bot := by simp [stoneValue]
      top := by
        have hp : (⊤ : B) ∉ p.ideal := p.isPrime.toIsProper.top_notMem
        simp [stoneValue, hp]
      additive := ?_
      nonnegative := ?_ }
  ·
    intro a b h
    have hs := congrArg (fun f : PrimePoint B →ᵇ ℝ => f p)
      (stoneIndicator_sup_of_disjoint B h)
    simpa [stoneIndicator_apply] using hs
  ·
    intro a
    simp only [stoneValue]
    split <;> norm_num

@[simp]
theorem primeProbability_apply (p : PrimePoint B) (a : B) :
    (primeProbability B p).1 a = stoneValue B a p :=
  rfl

@[simp]
theorem eventVector_apply (a : B) (p : ProbabilityPoint B) :
    eventVector B a p = p.1 a :=
  rfl

@[simp]
theorem eventVector_bot : eventVector B (⊥ : B) = 0 := by
  ext p
  exact p.2.bot

@[simp]
theorem eventVector_top : eventVector B (⊤ : B) = 1 := by
  ext p
  exact p.2.top

@[simp]
theorem eventVector_sup_of_disjoint {a b : B} (h : Disjoint a b) :
    eventVector B (a ⊔ b) = eventVector B a + eventVector B b := by
  ext p
  exact p.2.additive a b h

/-- Probability-evaluation vectors are also a faithful representation of events. -/
theorem eventVector_injective : Function.Injective (eventVector B) := by
  intro a b hab
  apply stoneIndicator_injective B
  ext p
  have h := congrArg (fun f : ProbabilityPoint B →ᵇ ℝ =>
    f (primeProbability B p)) hab
  exact h

@[simp]
theorem event_apply (a : B) (p : ProbabilityPoint B) :
    (event B a : ProbabilityPoint B →ᵇ ℝ) p = p.1 a :=
  rfl

@[simp]
theorem event_bot : event B (⊥ : B) = 0 := by
  apply Subtype.ext
  exact eventVector_bot B

@[simp]
theorem event_top_coe :
    ((event B (⊤ : B) : EventSpan B) : ProbabilityPoint B →ᵇ ℝ) = 1 :=
  eventVector_top B

@[simp]
theorem event_sup_of_disjoint {a b : B} (h : Disjoint a b) :
    event B (a ⊔ b) = event B a + event B b := by
  apply Subtype.ext
  exact eventVector_sup_of_disjoint B h

/-- Pointwise positivity for a functional on the event span. -/
def IsPositive (L : EventSpan B →L[ℝ] ℝ) : Prop :=
  ∀ f : EventSpan B,
    (∀ p : ProbabilityPoint B, 0 ≤ (f : ProbabilityPoint B →ᵇ ℝ) p) →
      0 ≤ L f

/-- A positive normalized bounded linear functional on the universal event span. -/
structure PositiveState where
  functional : EventSpan B →L[ℝ] ℝ
  positive : IsPositive B functional
  normalized : functional (event B ⊤) = 1

/-- Evaluation at a finitely additive probability is a positive normalized state. -/
def probabilityToState (p : ProbabilityPoint B) : PositiveState B where
  functional :=
    (BoundedContinuousFunction.evalCLM ℝ p).comp (EventSpan B).subtypeL
  positive := by
    intro f hf
    exact hf p
  normalized := by
    exact p.2.top

@[ext]
theorem PositiveState.ext {S T : PositiveState B}
    (h : S.functional = T.functional) : S = T := by
  cases S
  cases T
  simp_all

/-- A positive normalized state restricts to a finitely additive probability on events. -/
def stateToProbability (S : PositiveState B) : ProbabilityPoint B := by
  refine ⟨fun a => S.functional (event B a), ?_⟩
  refine
    { bot := by simp
      top := S.normalized
      additive := ?_
      nonnegative := ?_ }
  ·
    intro a b h
    rw [event_sup_of_disjoint B h, map_add]
  ·
    intro a
    apply S.positive
    intro p
    exact p.2.nonnegative a

@[simp]
theorem stateToProbability_apply (S : PositiveState B) (a : B) :
    (stateToProbability B S).1 a = S.functional (event B a) :=
  rfl

@[simp]
theorem stateToProbability_probabilityToState (p : ProbabilityPoint B) :
    stateToProbability B (probabilityToState B p) = p := by
  apply Subtype.ext
  funext a
  rfl

theorem probabilityToState_stateToProbability (S : PositiveState B) :
    probabilityToState B (stateToProbability B S) = S := by
  cases S with
  | mk L hpos hnorm =>
      apply PositiveState.ext
      apply ContinuousLinearMap.ext
      intro f
      change f.1 (stateToProbability B ⟨L, hpos, hnorm⟩) =
        L f
      refine Submodule.span_induction
        (p := fun g hg =>
          g (stateToProbability B ⟨L, hpos, hnorm⟩) =
            L ⟨g, hg⟩) ?_ ?_ ?_ ?_ f.2
      · intro g hg
        rcases hg with ⟨a, rfl⟩
        rfl
      · change 0 = L 0
        simp
      · intro x y hx hy hx' hy'
        change x (stateToProbability B ⟨L, hpos, hnorm⟩) +
            y (stateToProbability B ⟨L, hpos, hnorm⟩) =
          L (⟨x, hx⟩ + ⟨y, hy⟩)
        rw [map_add, hx', hy']
      · intro c x hx hx'
        change c * x (stateToProbability B ⟨L, hpos, hnorm⟩) =
          L (c • ⟨x, hx⟩)
        rw [map_smul, hx']
        simp [smul_eq_mul]

/-- Finitely additive probabilities and positive normalized states on `EventSpan`
are canonically equivalent. -/
def probabilityStateEquiv : ProbabilityPoint B ≃ PositiveState B where
  toFun := probabilityToState B
  invFun := stateToProbability B
  left_inv := stateToProbability_probabilityToState B
  right_inv := probabilityToState_stateToProbability B

end

end Scott1964.MeasurementStructures.Probability.Infinite
